# Generated by Django 4.2.7 on 2023-11-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishnatravelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
